# Generated by Django 5.1.1 on 2024-09-28 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wardrobe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateTimeField(auto_now_add=True)),
                ('recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wardrobe.clothes')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
