# Generated by Django 5.1.1 on 2024-09-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='clothes_images/')),
                ('category', models.CharField(choices=[('T-shirt', 'T-shirt'), ('Jeans', 'Jeans'), ('Jacket', 'Jacket')], max_length=50)),
                ('is_old', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
